### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by Vilican** [InventivetalentDev/PacketListenerAPI#1]
## What steps will reproduce the problem?
1. Start server
2. Wait
## What were you expecting to happen? What happened instead?

I expected normal server start. However, errors showed up.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

`15:54:27 [INFO] PacketListenerApi version 3.4.2`
## What Spigot version are you using? _Type /version_

`15:53:55 [INFO] This server is running Paper version git-Paper-788 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)`
## What plugins ae you using? _Type /plugins_

`15:53:26 [INFO] Plugins (52): SecretDoors, NTApi, iConomy_Recreation, Websend, TuxTwoLib, OneWayBlocks, Pl3xMOTD, MultiWorld, SkinsRestorer, uCommands, ChatMoney, AntiCursePro, ParticleLIB, MaintenanceMode, AutoRespawnPLUS-1.9, AFK, LoginSecurity, PacketListenerApi, ClearLag, AdvancedBan, MCAntiVirus, ChopTreeW, ProtocolLib, AntiWDL, AdvancedPortals, FastAsyncWorldEdit, QueuedCommands, OpGuard, PermissionsEx, TimeIsMoney, Vault, aFreeze, MassiveCore, SpyCraft-Reporting, PerWorldInventory, ASkyBlock, ChatManager, WorldEdit, TreasureChest, Citizens, Sentinel, ColorMe, CouponCodes, WorldGuard, Quests, MyPet, CompatNoCheatPlus, NoCheatPlus, CraftBook, WorldGuardFix, ChestShop, NTAC`
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

http://pastebin.com/wQDqfrhq
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Yes, it did, but it was v3.4.1 on 1.9.4.

**Comment by InventivetalentDev** [comment]
Please download this plugin: https://github.com/InventivetalentDev/ClassLoaderDebug/releases
Run '/cldb org.inventivetalent.reflection.util.AccessUtil' and post the output.

**Comment by Vilican** [comment]
Is it this?

```
16:54:14 [INFO]   Class: class org.inventivetalent.reflection.util.AccessUtil
16:54:14 [INFO]  Loader: org.bukkit.plugin.java.PluginClassLoader@1c809e61
16:54:14 [INFO]  Plugin: OneWayBlocks by [inventivetalent]
```

**Comment by InventivetalentDev** [comment]
Yep, that's what I needed. I'll update OneWayBlocks with the proper classes, then it should work.

**Comment by Vilican** [comment]
> I'll updated

Will or is it already done? If it is, where I can download the new copy?

**Comment by InventivetalentDev** [comment]
Sorry for the typo. I just posted the update.
