### ISSUE TITLE
Wont work for 1.12

### ISSUE THREAD

**Issue by 6unsatiable** [InventivetalentDev/PacketListenerAPI#14]
## What steps will reproduce the problem?  
1. starting the server

## What were you expecting to happen? What happened instead?  
i was expecting it to make a folder
and it didnt

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.6.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Spigot-99c2a37-381

## What plugins are you using? *Type /plugins*  
 TPA, WorldEdit, PacketListenerApi, SetSpawn, CustomRecipes, ProtocolLib, WorldGuard, AutoSaveWorld, NoCheatPlus, ParticleCapes, PhantomAdmin, iConomy, PermissionsEx, KeepChunks, ServerListPlus, Vault, MyCommand, SelectionVisualizer, DakataAntiCheat, AuthMe, ChangeSkin, DiscordSRV, BossShopPro, RandomTeleport, CookieMonster, ServerSigns, BedHome, MyHome, PlayerShops

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
the only things in the console involving the plugin
[PacketListenerApi] Loading PacketListenerApi v3.6.0-SNAPSHOT
[PacketListenerAPI] Using INChannel

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
nope

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
if im not using it correctly or it doesnt make a folder or something.   please give me some resources to use to figure out how to use it.     please

**Comment by InventivetalentDev** [comment]
Not all plugins create a plugin folder. Doesn't mean it's broken.

**Comment by InventivetalentDev** [comment]
If you want examples, just read the plugin page properly 
![](https://i.inventivetalent.org/2017/08/10/e7dae79193_chrome.png)

**Comment by 6unsatiable** [comment]
i know i sound pretty stupid.         yea but where do i put those if i were to try to read packets
