### ISSUE TITLE
How to get channel name for incoming packet

### ISSUE THREAD

**Issue by VariableVixen** [InventivetalentDev/PacketListenerAPI#19]
I'm using PacketListenerAPI 3.6.0-SNAPSHOT and I'm trying to get the name of a packet's channel. The problem is I can't figure out how.

I'm trying to write a plugin that allows clients to use the [Ping mod for Forge](https://github.com/dmillerw/Ping) on my private spigot server. It sends `PacketPlayInCustomPayload` to the server to be forwarded to the connected players so they can see the ping location. In their code, I can see that they're using the channel `ping` but I can't figure out how to tell what channel an incoming packet is on.

**Comment by InventivetalentDev** [comment]
The `PacketPlayInCustomPayload` has a 'tag' field, which specifies the channel.
