### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [InventivetalentDev/PacketListenerAPI#2]
start code
http://pastebin.com/3Sz8cWTx

timings
https://timings.aikar.co/v2/?id=f4628ef5842d43f38b64545ca5431b2c

logs
http://pastebin.com/GicLn6LH

**Comment by InventivetalentDev** [comment]
That shouldn't cause any further issues. Since you ignored the template and didn't provide any more details, I'll just assume this didn't cause any issues.
