### ISSUE TITLE
Maven repo missing org.inventivetalent.spiget-update:bukkit:jar:1.4.

### ISSUE THREAD

**Issue by RoboMWM** [InventivetalentDev/PacketListenerAPI#22]
[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project org.inventivetalent.packetlistener:api:jar:3.7.2-SNAPSHOT: Failure to find org.inventivetalent.spiget-update:bukkit:jar:1.4.1 in https://repo.inventivetalent.org/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of inventive-repo has elapsed or updates are forced -> [Help 1]

Can you add this to your maven repo?

**Comment by InventivetalentDev** [comment]
should be in the repo now c:
