### ISSUE TITLE
Start up failure on papermc

### ISSUE THREAD

**Issue by Chveer** [InventivetalentDev/PacketListenerAPI#31]
## What steps will reproduce the problem?  
1. Placing .jar in plugins folder
2. Started server
3. FAiled start up

## What were you expecting to happen? What happened instead?  
Start up but did not start up
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
04.07 02:04:45 [Server] INFO PacketListenerApi version 3.7.3-SNAPSHOT
## What Spigot version are you using? *Type /version*  
04.07 02:05:45 [Server] INFO This server is running Paper version git-Paper-123 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
04.07 02:06:03 [Server] INFO Plugins (46): ActionAnnouncer, AdvancedPortals, ArmorStandEditor, Citizens, CoreProtect, CraftBay, DiscordSRV, EnjinMinecraftPlugin, EpicRename, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, Item2Chat, JupiterCore, mcMMO, MCSF*, MineableSpawners, MoneyNote*, Multitool, Multiverse-Core*, Multiverse-Inventories*, MultiWorldMoney*, MyPet, PacketListenerApi*, Parkour, PermissionsEx*, PlaceholderAPI*, PlayerReport*, ProtocolLib, QuantumShop, QuestionBot*, Quests, Rankup, SuperTrails*, Vault, VoidGenerator, Votifier, VotingPlugin, VoxelSniper*, Wild, WorldBorder, WorldEdit, WorldGuard
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/aCRSTF8i
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No this did work previously however

**Comment by magmiy** [comment]
Getting the same issue...
