### ISSUE TITLE
PacketListenerAPI spamming WARNS exception occured while trying to execute 'onSend' in plugin GlowAPI - 1.14.4

### ISSUE THREAD

**Issue by axemwa** [InventivetalentDev/PacketListenerAPI#32]
## What steps will reproduce the problem?  
1. Start 1.14.4 Paper server with GlowAPI and PacketListenerAPI installed in plugin folder
2. Join server
3. Watch as the spamms create a 10mb latest.log in 30 seconds

## What were you expecting to happen? What happened instead?  
No spamms
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
PacketListenerAPI 3.7.3 SNAPSHOT (latest)
GlowAPI version 1.4.8-SNAPSHOT (latest)
## What Spigot version are you using? *Type /version*  
Paper-137 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT) 
## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/37608633/61696903-55933380-ad75-11e9-9308-c254f3dba1d8.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/m586qV4k

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No did not crash but spammed like crazy
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm using ProtocolSupport which handles packets, mainly allows different client versions to join the server

**Comment by Th3Shadowbroker** [comment]
Hi @axemwa,
please update your version of GlowAPI to [1.4.9](https://github.com/InventivetalentDev/GlowAPI/releases/tag/1.4.9-SNAPSHOT). However you might still experience some errors showing up as mentioned in https://github.com/InventivetalentDev/GlowAPI/issues/22

**Comment by axemwa** [comment]
ok thnx will do

**Comment by axemwa** [comment]
so far so good I think it's safe to close the issue for now :) tyvm
