### ISSUE TITLE
Error on 1.14.4

### ISSUE THREAD

**Issue by Qballl** [InventivetalentDev/PacketListenerAPI#33]
The API is having issues enabling on 1.14.3 and 1.14.4. Here is pastebin https://pastebin.com/7qatGqQ2 online line used in StaffPlus is         APIManager.initAPI(PacketListenerAPI.class);

**Comment by InventivetalentDev** [comment]
This looks like a really strange error, where it fails to find a class that's actually included in PacketListenerAPI. Which artifact are you using as a dependency?

**Comment by Qballl** [comment]
Here is everything from my pom for packetlistenerapi https://pastebin.com/wE4YG6wV

**Comment by InventivetalentDev** [comment]
Could you please check if your plugin's binary contains the `org.inventivetalent.packetlistener.channel.INCChannel` class?  
It should be included in the 1_8 artifact, are you shading everything for PLA?

**Comment by Qballl** [comment]
Everything for PLA is being shaded or should be I'll check the jar in a few hours when I'm home

**Comment by Qballl** [comment]
That class is missing

**Comment by InventivetalentDev** [comment]
Then there's likely an issue with your jar shading.

**Comment by Qballl** [comment]
Would you mind looking at the pom https://github.com/Qballl/StaffPlus/blob/master/StaffPlusCore/pom.xml I am 99% sure I've not changed anything recently

**Comment by InventivetalentDev** [comment]
I couldn't see anything that appeared wrong with it, though I also couldn't compile it (missing craftbukkit stuff on my pc) to actually play around with it.  
You mentioned it worked before though, right? Commit history shows the (https://github.com/Qballl/StaffPlus/commit/11740d9a4483c1c930b479fb96aedf71eab5a6ed#diff-09a8735fad9578297c727b7b44f4f589)[`minimizeJar` setting being added], so maybe that's doing weird stuff to the shading... Just taking guesses here, really.

**Comment by Qballl** [comment]
Alright I'll see about that thanks

**Comment by Qballl** [comment]
That was it thank you so much for your help
