### ISSUE TITLE
ChannelAbstract Bug 1.14

### ISSUE THREAD

**Issue by FunkyNico** [InventivetalentDev/PacketListenerAPI#34]
## What steps will reproduce the problem?  
1. Download the plugin and install it on the /plugins folder.
2. Start the server.
3. See the error.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

PacketListenerApi version 3.7.3-SNAPSHOT

## What Spigot version are you using? *Type /version*

Paper version git-Paper-167 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  

AdvancedLogin*, Essentials, EssentialsChat, EssentialsSpawn, FastLogin*, LuckPerms, Multiverse-Core, OreReplacerPlugin, PacketListenerApi*, ProtocolLib, ProtocolSupport, React*, SkinsRestorer, StaffPlus, TreeGravity, Vault, ViaVersion*, WorldEdit, WorldGuard

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/D7mLbj0C

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

I'm not using bungeecord, it's a simple server.

**Comment by Kqliber** [comment]
I too am getting the same error.
