### ISSUE TITLE
Staff+ enable error (built in packetlistenerapi)

### ISSUE THREAD

**Issue by CodeGourami** [InventivetalentDev/PacketListenerAPI#40]
## What steps will reproduce the problem?  
1.  Install Staff+ release 3.2.9 ( https://github.com/Qballl/StaffPlus/releases )
2.  Use Paper 1.14.4 build #187
3.  Start server

## What were you expecting to happen? What happened instead?  
No error messages. but saw error message
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*   
Built in version in Staff+ plugin 

## What Spigot version are you using? *Type /version*  
Paper 1.14.4 #187

## What plugins are you using? *Type /plugins*  
ProtocolLib and Staff+ are only relevant plugins
(Will not share entire plugin list)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/SCQ7b33i

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No it did not

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

Had the issue before since update from 1.14.3 to 1.14.4 but thought it was due to Staff+ having been broken in 1.14.4. I stopped using Staff+ up till now and upon reporting this they said it was a packetlistenerapi issue. 

Thanks for your time.

**Comment by yannicklamprecht** [comment]
That's a merge conflict in staff+. 

https://github.com/Qballl/StaffPlus/blame/master/StaffPlusCore/pom.xml
