### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by srnyx** [InventivetalentDev/PacketListenerAPI#45]
## What steps will reproduce the problem?  
1. Download version 3.7.3 of PackerListenerAPI
2. May have something to do with StaffPlus, so download version 3.3.0.0 of that too
3. Run the server

## What were you expecting to happen? What happened instead?  
I expected no errors to occur. But it didn't enable the plugin.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.3.0.0
## What Spigot version are you using? *Type /version*  
git-Paper-135
## What plugins are you using? *Type /plugins*
Relevant: PacketListenerAPI, StaffPlus, any other plugins that may use PacketListenerAPI
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/LBgWYef2
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am not using BungeeCord, yes I think it worked before. This might be the reason StaffPlus is not working.

**Comment by srnyx** [comment]
Is someone going to assist me with this because it is causing problems with other main plugins on my server as well.

**Comment by InventivetalentDev** [comment]
The log you posted really doesn't contain much helpful information, Please post your full server/error log.

**Comment by srnyx** [comment]
https://pastebin.com/gxtt5SMj

**Comment by InventivetalentDev** [comment]
Looks like one of the plugins you have installed might be outdated.

**Comment by srnyx** [comment]
Wouldn't it tell me in the console?

**Comment by srnyx** [comment]
Like wouldn't the plugin that is outdated tell me that?
Because I have a lot of plugins, and going through them all would take forever.

**Comment by InventivetalentDev** [comment]
It's likely something which uses an outdated version of https://github.com/InventivetalentDev/SpigetUpdater to do update checks.

**Comment by srnyx** [comment]
Still relevant, not fixed yet
The plugin still won't enable

**Comment by srnyx** [comment]
Issue has been fixed
