### ISSUE TITLE
Error when Player disconnects to quick

### ISSUE THREAD

**Issue by SpraxDev** [InventivetalentDev/PacketListenerAPI#5]
I hope PacketListenerAPI is the reason for the error. But I know that a packet of one of your Plugins is called (I'm not using its API only NickNamer from you)
## What steps will reproduce the problem?

I'm checking the UUID with a BungeeCord-Plugin. While connecting to specified Servers. When someone joins but is getting "kicked" by the Plugin.
## What were you expecting to happen? What happened instead?

No error o.O
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

PacketListenerApi version 3.4.4
## What Spigot version are you using? _Type /version_

 This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
## What plugins are you using? _Type /plugins_

Plugins (10): PermissionsEx, MCWebi, EmptyWorldGenerator, BlockLaby, ServerUtils, PacketListenerApi, ProtocolLib, NoCheatPlus, NickNamer, LobbyHandler
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

http://pastebin.com/W6GAY3FS
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

no crasg
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

I told you at "What steps will reproduce the problem?" - My Code: http://pastebin.com/aSXevY33

**Comment by InventivetalentDev** [comment]
This is probably caused by your code manually disconnecting the player's connection, which messes up the login state on the spigot servers. 
Try utilizing the LoginEvent's methods of kicking the player (#setCancelled & #setCancelReason), that should properly disconnect them.  
I'll probably add a separate check in a future version to avoid players from being kicked by errors.

**Comment by SpraxDev** [comment]
Ok great - My Code will kick the player before he can connect to the Spigot Server so no error anymore. Thanks :smile:
