### ISSUE TITLE
Minor server error on load up

### ISSUE THREAD

**Issue by Jadiction** [InventivetalentDev/PacketListenerAPI#55]
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
StaffPlus version 3.3.1.0
## What Spigot version are you using? *Type /version*  
This server is running Paper version git-Paper-50 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
StaffPlus
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/raw/ZEZNrzKE
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
While loading up StaffPlus, I seem to get this warning that PacketListenAPI is not yet initialized then some other warnings are provided. The plugin seems to be working fine, but as of right now I have an error-less console other than this one and it'd be awesome to get it fixed/optimized. Thanks!

**Comment by Jadiction** [comment]
It is still relevant.

**Comment by InventivetalentDev** [comment]
You can safely ignore this warning. I'll remove it when another general update is needed.
