### ISSUE TITLE
Crash when start with my plugin

### ISSUE THREAD

**Issue by CamillePele** [InventivetalentDev/PacketListenerAPI#58]
## What steps will reproduce the problem?  
1. Start the server with my plugin and your

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*
the lastest

## What Spigot version are you using? *Type /version*  
This is a final build for 1.12.2

## What plugins are you using? *Type /plugins*  
NickNamer and my own skin plugin

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No my client don't crash

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
My plugin use NickNamer API

Server Log Error:
https://pastebin.com/7hYVP8yA

**Comment by InventivetalentDev** [comment]
Looks like you're probably loading PLA twice; some code snippets of your plugin would be helpful. Also, in case you're shading PLA/NN into your plugin - don't, install them separately and depend on them in your plugin.yml

**Comment by CamillePele** [comment]
Sorry to disturb you, I start with spigot and I hadn't added PLA in plugin.yml like dependence.
Thanks you for your help
