### ISSUE TITLE
java.lang.NoSuchFieldException: list

### ISSUE THREAD

**Issue by MorkaZ** [InventivetalentDev/PacketListenerAPI#59]
Using latest paper 1.15.2 and protocolsupport.
Getting this exception on server start/plugin load
https://pastebin.com/VNktic8h

**Comment by InventivetalentDev** [comment]
You should be able to ignore that. Also, please use the template in future issues.

**Comment by Dymeth** [comment]
> You should be able to ignore that.

Perhaps you should correctly handle this exception to avoid similar issues in the future?
