### ISSUE TITLE
Issue Enabling PacketListenerAPI with Thermos 1.7.10

### ISSUE THREAD

**Issue by Samkist** [InventivetalentDev/PacketListenerAPI#63]
## What steps will reproduce the problem?  
1.  Usage of Thermos as a server jar
2.  Attempted installation of PacketListenerAPI

## What were you expecting to happen? What happened instead?  
I was expecting PacketListenerAPI to enable as it displays 1.7.10 compatibility. It failed to enable and I received the error log down below.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
PacketListenerAPI_v3.7.6-SNAPSHOT
## What Spigot version are you using? *Type /version*  
I am using Thermos-1.7.10-1558-build-57
## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/24465284/80050688-57e11480-84e4-11ea-886c-18716438dbdc.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://rythm.online/awiqisuzem.css (Just a hastebin)
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am using Thermos 1.7.10 I am aware that this is potentially an issue and it might have caused it but I am unsure of this.

**Comment by dinobossytnew** [comment]
It happens to me too, can you help me?
