### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by srnyx** [InventivetalentDev/PacketListenerAPI#68]
## What steps will reproduce the problem?  
1. Use PacketListenerAPI on a 1.14.4 server

## What were you expecting to happen? What happened instead?  
No error
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Don't know, doing /version doesn't work
## What Spigot version are you using? *Type /version*  
Paper version git-Paper-219 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
ActionBarAPI, AsyncWorldEdit, AutoSync, BasicAntiCheat, ChatColor2*, ChatReaction, ClearLag, CoreProtect, CrazyEnchantments, DiscordSRV, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, HubBasics, InteractiveChat, IridiumSkyblock, KillerMoney*, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, NetworkCore, PlaceholderAPI, PlayerRanks*, ProtocolLib, RankGrantPlus, Scoreboard-ReRevision*, Scoreboard-revision*, SilkySpawners, SkinsRestorer, StaffPlus, SuperVanish, UltimateStacker, Vault, VentureChat, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/2caQtJgb
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Bungeecord, I think the plugin StaffPlus is loading PacketListenerAPI, because I have no .jar of PLAPI

**Comment by InventivetalentDev** [comment]
The only error by PLA I can see should be safe to ignore.
