### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by QueenKisaki** [InventivetalentDev/PacketListenerAPI#7]
http://pastebin.com/sutkL9bd

using spigot 1.10.2 and updated animated frames and its dependencies. 
Seems to throw errors on packetlistenerapi tho. 
I've downgraded the api until this fixed but the frames won't load. 
could just downgrade AF and mapmanager but hoping the update 
would fix it trying to load deleted frames.......

**Comment by InventivetalentDev** [comment]
Please use the provided issue template.

**Comment by QueenKisaki** [comment]
## What steps will reproduce the problem?  
1. updating all related plugins to AF
2. restarting server
3. 

## What were you expecting to happen? What happened instead?  

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
~~Packetlistener 3.4.4 (Trying to update)~~
3.5.0
## What Spigot version are you using? *Type /version*  
1.10.2
## What plugins are you using? *Type /plugins*  
https://s29.postimg.org/nvff8vvjr/plugins.png
Plugins list

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://pastebin.com/sutkL9bd
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No bungee and it worked with minor errors (trying to load deleted frames)

**Comment by InventivetalentDev** [comment]
Please try if it works on a separate server without any other plugins. I don't see anything wrong with the current version, so it's probably something on your server interfering.

**Comment by QueenKisaki** [comment]
I dont have another server atm but after your fix this is what comes up: http://pastebin.com/yj4Nw5PV

**Comment by InventivetalentDev** [comment]
You're running another outdated plugin which has ReflectionHelper included.
