### ISSUE TITLE
Tutorial example outdated or unclear

### ISSUE THREAD

**Issue by IamMusavaRibica** [InventivetalentDev/PacketListenerAPI#76]
The whole code: https://hastebin.com/ufoyonisit.java
## What were you expecting to happen? What happened instead?  
Expect: The onSend and onReceive methods inside `new PacketHandler () {    }` to be called
What happened: They didn't get called.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.7.8-SNAPSHOT
## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-Spigot-a99063f-be6aaf0 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
This is the only plugin I'm using
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No errors occured
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
None

**Comment by Gamer08YT** [comment]
Hey Bro,
you need to init the Plugin Instance by adding your instance to the PacketHandler Constructor.

Regards,
Jan Heil

**Comment by IamMusavaRibica** [comment]
I already did that (seeing the deprecation warning), but the problem was
the server was loading my plugin before PacketListenerAPI
Adding a depend or softdepend to my plugin fixed it
Thank you anyway

pon, 30. stu 2020. u 19:13 Jan Heil <notifications@github.com> napisao je:
