### ISSUE TITLE
Hi, i got this issue on 1.11.2

### ISSUE THREAD

**Issue by MADS0LADEN** [InventivetalentDev/PacketListenerAPI#8]
## What steps will reproduce the problem?  
1. Drop the .jar file into the /plugins folder ;)
2. Start the server
3. voilà

## What were you expecting to happen? What happened instead? 
The plugin would load, but no 👎 

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
The latest (3.5.0)

## What Spigot version are you using? *Type /version*  
git-Spigot-4741400-a1d3777 (MC: 1.11.2)

## What plugins are you using? *Type /plugins*  
MapManager & AnimatedFrames (they're both red)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://hastebin.com/eqibejezey.sql

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No. The plugin did not load.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Nope, none of that.

**Comment by InventivetalentDev** [comment]
This isn't really an issue specific to 1.11.2, is it? Did you try another version?

**Comment by MADS0LADEN** [comment]
Also does it on 1.10.2

**Comment by MADS0LADEN** [comment]
And 1.9.4

**Comment by MADS0LADEN** [comment]
And 1.8.8

**Comment by CleanerOrc** [comment]
Same error.  [http://pastebin.com/0mP5VJeC](url)
Spigot 1.11.2

**Comment by InventivetalentDev** [comment]
Alright, seems like the Travis-CI build didn't properly shade the updater libraries, which is why I wasn't able to reproduce the problem with the jars I compiled locally.

**Comment by InventivetalentDev** [comment]
Please try the [3.5.1-SNAPSHOT](https://github.com/InventivetalentDev/PacketListenerAPI/releases/tag/3.5.1-SNAPSHOT). Should be working as intended now.

**Comment by MADS0LADEN** [comment]
Thank you! :)
