### ISSUE TITLE
Java Runtime class file error

### ISSUE THREAD

**Issue by itsacrimetorhyme** [InventivetalentDev/PacketListenerAPI#81]
## What steps will reproduce the problem?  
1. install plugin on 1.16.5 spigot server
2. run server
3. 

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

3.8.0

## What Spigot version are you using? *Type /version*  
1.16.5

## What plugins are you using? *Type /plugins*  
CoreProtect, dynmap, floodgate-bukkit, Geyser-Spigot, NametagEdit, Chunky

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/LwTCztaQ

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

no

**Comment by yannicklamprecht** [comment]
You're running Java 8 and this plugin is compiled using java 9. I recommend running the server using java 11.

3.8.0 should work with Java 8.

**Comment by itsacrimetorhyme** [comment]
https://www.oracle.com/java/technologies/javase/javase9-archive-downloads.html

downloading and installing this fixed the issue. Thanks for the help!
