### ISSUE TITLE
Pops when server starts

### ISSUE THREAD

**Issue by Koulis17** [InventivetalentDev/PacketListenerAPI#84]
>....WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.inventivetalent.packetlistener.reflection.util.AccessUtil (file:/home/container/plugins/PacketListenerAPI_v3.8.0-SNAPSHOT.jar) to class java.lang.reflect.Field
WARNING: Please consider reporting this to the maintainers of org.inventivetalent.packetlistener.reflection.util.AccessUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by dinobossytnew** [comment]
f

**Comment by Koulis17** [comment]
?

**Comment by Koulis17** [comment]
>....WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.inventivetalent.packetlistener.reflection.util.AccessUtil (file:/home/container/plugins/PacketListenerAPI_v3.8.0-SNAPSHOT.jar) to class java.lang.reflect.Field
WARNING: Please consider reporting this to the maintainers of org.inventivetalent.packetlistener.reflection.util.AccessUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[02:24:49 INFO]: [PacketListenerAPI] Using INChannel
