### ISSUE TITLE
Player and Adress is only null

### ISSUE THREAD

**Issue by ManiecTV** [InventivetalentDev/PacketListenerAPI#9]
## What steps will reproduce the problem?  
When i use "ReceiverPacket" player and username is only null.

## What were you expecting to happen? What happened instead?  
- I use "packet.getChannel().getRemoteAddress()" or "packet.getPlayer()" and is only null

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
-PacketListenerAPI 3.5.2-SNAPSHOT

## What Spigot version are you using? *Type /version*  
-PaperSpigot 1.8.0 (on 1.7 its same)

## What plugins are you using? *Type /plugins*  
-My plugins that certainly do not interfere

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
- https://pastebin.com/guBtKbVJ

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
- no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
- clear paperspigot server

**Comment by InventivetalentDev** [comment]
Can you check if you also receive a second packet where the player isn't `null`?
