### ISSUE TITLE
Plugin didn't even load

### ISSUE THREAD

**Issue by Bartek200219** [InventivetalentDev/PacketListenerAPI#91]
## What steps will reproduce the problem?  
1. Install pugin on newest paper

## What were you expecting to happen? What happened instead?  
Server should load the plugin without any problems.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.9.0-SNAPSHOT
## What Spigot version are you using? *Type /version*  
Paper-700 (also tested on paper-505) 1.16.5
## What plugins are you using? *Type /plugins*  
StaffPlus
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/6J9v4kgL
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by HexedHero** [comment]
Update to Java 11 at least.

**Comment by Bartek200219** [comment]
After running server with Java 11 everything works. Please add this info in readme and/or spigot site
