### ISSUE TITLE
Error message on 1.17 every time a player joins

### ISSUE THREAD

**Issue by AlessioGr** [InventivetalentDev/PacketListenerAPI#99]
## What steps will reproduce the problem?  
1. Join the server
2.
![image](https://user-images.githubusercontent.com/70709113/123995159-55bef380-d9ce-11eb-84e6-fbbd30ad8318.png)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
PacketListenerApi v3.9.3-SNAPSHOT

## What Spigot version are you using? *Type /version*  
![image](https://user-images.githubusercontent.com/70709113/123995249-6a9b8700-d9ce-11eb-84ed-0aa77557eddc.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/raw/DJ9HMmXQ

**Comment by iHDeveloper** [comment]
@AlessioGr Please use the latest version of the plugin. You can download it from [here](https://github.com/InventivetalentDev/PacketListenerAPI/releases/tag/3.9.5-SNAPSHOT)

**Comment by Darkweasam** [comment]
> 
> 
> @AlessioGr Please use the latest version of the plugin. You can download it from [here](https://github.com/InventivetalentDev/PacketListenerAPI/releases/tag/3.9.5-SNAPSHOT)

He probably used this version because the spigot page has the 3.9.3 as "latest" - I had to come here aswell to find it out this issue has been patched. Anyway, thank you!

**Comment by LoneDev6** [comment]
It works fine on 1.17.1
